apiVersion: compute.gcp.upbound.io/v1beta1
kind: Disk
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/disk
  labels:
    testing.upbound.io/example-name: bastion_disk_ubuntu2304
  name: bastion-disk-ubuntu2304
spec:
  forProvider:
    description: Persistent disk for bastion instances.
    image: projects/web-project-init/global/images/bastion-storage-image-ubuntu2304
    ## Other source option - snapshot
    # snapshot: projects/web-project-init/global/snapshots/bastion-snapshot-ubuntu2304
    labels:
      environment: dev
    physicalBlockSizeBytes: 4096
    project: web-project-init
    size: 10
    type: pd-balanced
    zone: europe-west3-a
