apiVersion: compute.gcp.upbound.io/v1beta1
kind: InstanceTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/instancetemplate
  labels:
    testing.upbound.io/example-name: bastion_instance_ubuntu2304_template
  name: bastion-instance-ubuntu2304-template
spec:
  forProvider:
    canIpForward: false
    description: This template is used to create bastion instances.
    disk:
      - autoDelete: false
        boot: true
        deviceName: bastion-template
        diskSizeGb: 20
        diskType: pd-balanced
        mode: READ_WRITE
        sourceImage: projects/web-project-init/global/images/bastion-storage-image-ubuntu2304
    instanceDescription: Instance designated to be used as bastion.
    labels:
      environment: dev
    machineType: e2-micro
    metadata:
      environment: dev
    name: bastion-instance-template
    networkInterface:
      - subnetwork: "projects/web-project-init/regions/europe-west3/subnetworks/subnet-eu-west-192"
        stackType: IPV4_ONLY
    project: web-project-init
    reservationAffinity:
      - type: ANY_RESERVATION
    scheduling:
      - automaticRestart: true
        onHostMaintenance: MIGRATE
        provisioningModel: STANDARD
    serviceAccount: 
      - email: 85861670589-compute@developer.gserviceaccount.com
        scopes:
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring.write
          - https://www.googleapis.com/auth/servicecontrol
          - https://www.googleapis.com/auth/service.management.readonly
          - https://www.googleapis.com/auth/trace.append
    shieldedInstanceConfig:
      - enableIntegrityMonitoring: true
        enableSecureBoot: false
        enableVtpm: true
    tags:
      - instance
      - bastion
      - http-server
      - https-server