apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactapp-chart.fullname" . }}-service
  labels:
  {{- include "reactapp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: react-app
  {{- include "reactapp-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}